Repository andela/heimdal-ah-backend, pull requests merged in 2018-12, with the labels that each got.

#31 #162171021 implement article CRUD functionality
  .vscode/settings.json
  controllers/ArticlesController.js
  controllers/AuthController.js
  helpers/StatusResponse.js
  helpers/articleHelper.js
  helpers/generateSlug.js
  index.js
  lib/ArticleQueryModel.js
  middlewares/ArticleValidation.js
  middlewares/articleMiddleware.js
  middlewares/checkAuthentication.js
  migrations/20181208212602-create-articles.js
  migrations/20181210112344-create-ratings.js
  migrations/20181211141441-create-bookmarks.js
  models/articles.js
  models/bookmarks.js
  models/ratings.js
  models/users.js
  package-lock.json
  package.json
  routes/articles.js
  routes/index.js
  routes/users.js
  seeders/20181211173050-users-seeder.js
  seeders/20181212033227-profiles-seeder.js
  seeders/20181212076725-articles-seeder.js
  test/articles.js
  test/index.js
Labels: ready, review

#33 162171022 Give ratings to articles
  controllers/RatingsController.js
  index.js
  middlewares/RatingsMiddleware.js
  middlewares/checkAuthentication.js
  models/ratings.js
  models/users.js
  package-lock.json
  routes/index.js
  routes/ratings.js
  seeders/20181211173050-users-seeder.js
  test/articles.js
  test/ratings.js
Labels: ready

#38 Ft implement article readtime 162171032
  .gitignore
  controllers/ArticlesController.js
  helpers/articleHelper.js
  middlewares/articleMiddleware.js
  test/articles.js
  test/helpers/articleHelpers.js
  test/index.js
Labels: ready

#42 #162171029 Add pagination support to articles
  controllers/ArticlesController.js
  helpers/articleHelper.js
  helpers/checkIdentifier.js
  helpers/generateSlug.js
  helpers/pagination.js
  lib/ArticleQueryModel.js
  middlewares/articleExist.js
  routes/articles.js
  routes/bookmarks.js
  test/articles.js
Labels: ready, review

#49 [Feature #162171031]: refactor search/filter functionality
  controllers/ArticlesController.js
  controllers/SearchArticlesController.js
  helpers/pagination.js
  middlewares/ProfilesMiddleware.js
  middlewares/articleMiddleware.js
  test/search.js
Labels: ready, review

#48 #162171039 Functionality for users to highlight and comment on certain sections of an article
  controllers/ArticlesController.js
  controllers/AuthController.js
  controllers/HighlightsController.js
  events/index.js
  helpers/articleHelper.js
  helpers/eventEmitter.js
  helpers/generateEmailToken.js
  helpers/helper.js
  helpers/mailer.js
  index.js
  lib/ArticleQueryModel.js
  lib/highlightsLogic.js
  middlewares/articleMiddleware.js
  middlewares/checkArticle.js
  middlewares/highlightsMiddleware.js
  migrations/20181208212602-create-articles.js
  migrations/20181215225132-create-highlighted-texts.js
  models/articles.js
  models/highlightedtext.js
  routes/highlights.js
  routes/index.js
  test/articles.js
  test/bodyHelper.js
  test/helpers/mailer.js
  test/highlights.js
  test/index.js
  test/users.js
Labels: ready, review

#52 #162171038 add role based access control functionality
  controllers/ArticlesController.js
  controllers/AuthController.js
  controllers/RolesController.js
  controllers/UsersController.js
  helpers/articleHelper.js
  helpers/getToken.js
  index.js
  middlewares/ArticleValidation.js
  middlewares/RolesMiddleware.js
  middlewares/adminGuard.js
  middlewares/checkAuthentication.js
  models/users.js
  routes/admin.js
  routes/articles.js
  routes/index.js
  test/articles.js
  test/index.js
  test/middlewares/adminGuard.test.js
  test/readerStats.js
  test/roles.js
Labels: ready, review

#47 #162697923 comment can be made public
  controllers/CommentController.js
  lib/CommentQueryModel.js
  migrations/20181210235722-create-comments.js
  models/comments.js
  models/readerstats.js
  seeders/20181212081822-comments.js
  test/comments.js
Labels: review

#50 [feature 162171027] users notification WIP
  .gitignore
  controllers/ArticlesController.js
  controllers/CommentController.js
  controllers/FollowersController.js
  controllers/LikesController.js
  controllers/NotificationsController.js
  controllers/RatingsController.js
  controllers/RepliesController.js
  events/Notifications.js
  events/eventTypes.js
  events/handlers.js
  events/index.js
  events/socketIo.js
  helpers/likes.js
  helpers/mailer.js
  index.js
  lib/likes.js
  lib/notifications.js
  middlewares/checkAuthentication.js
  migrations/20181218073900-create-reports.js
  migrations/20181218122156-create-notifications.js
  models/notifications.js
  models/replies.js
  models/users.js
  package-lock.json
  package.json
  routes/index.js
  routes/notifications.js
  seeders/20181220172904-notification-seeders.js
  test/index.js
  test/notification.js
Labels: ready, review
